### ISSUE TITLE
Probleme de Player:removeMoney

### ISSUE THREAD

**Issue by nynjardin** [NastyZ98/FMS-NCG#3]
En suivant ce que j'ai trouvé sur la page de essentialMode base sur le forum de FiveM, j'ai utilisé la fonction pour prendre de l'argent au joueur. Cette fonction m'a généré une erreur

`[    457079] Error resuming coroutine: garage.lua:104: attempt to index a nil value (global 'Player')`
`[    457079] stack traceback:`
`[    457079] 	garage.lua:104: in function <garage.lua:84>`

Je me penche dessus des que j'ai compris ce qu'il se passe

**Comment by NastyZ98** [comment]
D'après ce que je lis, tu veux prendre l'argent du joueur lorsqu'il passe dans un garage pour la réparation du véhicule ? 

"Nil is a type with a single value, nil, whose main property is to be different from any other value. As we have seen, a global variable has a nil value by default, before a first assignment, and you can assign nil to a global variable to delete it. Lua uses nil as a kind of non-value, to represent the absence of a useful value." 

Essaye de voir si tu as des variables déclarés mais pas initialisé aux lignes indiqués

**Comment by nynjardin** [comment]
J'ai regardé et en fait j'essais d'appeler une fonction déclaré coté serveur, pas coté client... donc, en fait, pour n'importe quel script, a ce que je vois, il faudra une partie client et une serveur des que ça veut interagir avec l'argent. J'ai compris en regardant ça: https://github.com/FiveM-Scripts/FiveM-Taxi/blob/master/taxi_sv.lua

**Comment by NastyZ98** [comment]
Ah effectivement ils ont une fonction en plus

`TriggerClientEvent`

à la place du simple

`TriggerEvent`

**Comment by nynjardin** [comment]
Réglé ;)

J'ai fais tout appeler depuis le server et ça marche
