### ISSUE TITLE
Le menu qui déconne 

### ISSUE THREAD

**Issue by nynjardin** [NastyZ98/FMS-NCG#4]
Dans es_jobs/jobs_cl.lua il y la fonction qui appel le menu. 
Dans ce menu, la 1ere entrée est correct (si on tape la commande "/busJob" ça marche) mais elle génère une erreur dans la console du client (suffit de faire F8 pour la voir quand on a valider le 1er choix)

**Comment by ungarscool1** [comment]
Pour le dev: Je pense qu'il manque la fonction busJob dans le menu
`Menu.addButton("Chauffeur de Bus","busJob")` revoie à aucune fonction comme tous les boutons ils ne revoie à rien

**Comment by nynjardin** [comment]
On a changé de façon de faire:
`function MenuCallFunction(fnc, arg)
    if arg == nil then
        TriggerServerEvent(fnc)
    elseif arg ~= nil then
        TriggerServerEvent(fnc, arg)
    end
    --_G[fnc](arg)
end`
