### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by frederic2ec** [NastyZ98/FMS-NCG#7]
Bonjour,

Actuellement il n'y a aucune étape pouri l'installation.  Quel sont les étape pour installer les scripts. Pour l'instant c'est flou donc il faut ce casser la tete pour tenter d'installer le mods.
Merci!

**Comment by ungarscool1** [comment]
Bonsoir, 
Je ne suis pas le dev mais si tu veux/vous voulez installer un script par exemple pôle emploi tu va dans Plugins/es_jobs et tu installe/vous installez comme tout les autres mods
Après je dis peut-être une bêtise. Mais c'est généralement pareil

**Comment by frederic2ec** [comment]
Bonjour,

J'ai déja essayer, seulement plusieurs erreur sont citer dans la console donc je demandais si certain script devais etre installer d'une certaine facon ou s'il avais une certaine configuration a faire.

Merci!

**Comment by ungarscool1** [comment]
Bonjour, 
Je pense que c'est un bug puisque dans le #4 il y avait un problème de menu
À voir avec le dev puisque je n'ai pas bien compris comment il faisait son système de changement de job

**Comment by frederic2ec** [comment]
Bonjour,
Les erreus citer dans la console sont des fichiers manquant pour un scripts

Merci

**Comment by nynjardin** [comment]
Désolé mais normalement, c'est pas un script terminé, c'est pour ça qu'il n'y a aucun étape, quand un problème est sur Github, c'est pas forcement pour le partager, mais surtout pour s'organiser... Pour le moment, et étant donné que ce WiP, on ne fournis pas de support. Je vais ajouter un mot a ce sujet dans le readme quand on arrive sur ce Git. Pour savoir comment les choses évoluent, je vous recommande de suivre ce Git afin de voir la prochain release, qui elle, sera complète et fonctionnel
